Iterdataset
aditya-grover/climate-learn pull request #44
Opened 2023-02-03 07:19 UTC by tung-nd

This avoids loading all data into RAM in the beginning, but we'll have to trade off randomness. The idea is first to chunk the netcdf data into smaller npz files, and then load these files one by one. We shuffle these files and have to buffer to have some level of randomness.

2023-02-03 07:21 UTC, tung-nd commented
@jasonjewik @prakhar6sharma feel free to take a look when you have the time

2023-02-03 07:26 UTC, tung-nd commented
TODO:
- [ ] test on downscaling
- [ ] add time information (needed for visualization)

2023-02-03 07:30 UTC, tung-nd commented
Forgot to mention, the command to preprocess and chunk the netcdf data into npz files is
```
python src/climate_learn/data/nc2npz.py \
--root_dir /data0/datasets/weatherbench/data/weatherbench/era5/5.625deg/ \
--save_dir /data0/datasets/weatherbench/data/weatherbench/era5/5.625deg_npz \
--start_train_year 1979 --start_val_year 2016 --start_test_year 2017 --end_year 2018 \
--num_shards 16
```
I've already run this. The preprocessed data is in `/data0/datasets/weatherbench/data/weatherbench/era5/5.625deg_npz`

2023-02-04 02:26 UTC, jasonjewik commented on src/climate_learn/models/components/resnet.py
> -from .cnn_blocks import PeriodicConv2D, ResidualBlock, Upsample
Why was `Upsample` removed?

2023-02-04 02:27 UTC, jasonjewik commented on src/climate_learn/models/components/unet.py
> -        self.upsampling = upsampling
Why was upsampling removed?

2023-02-04 02:28 UTC, jasonjewik commented on src/climate_learn/models/components/vit.py
> -        upsampling=1,
Why was upsampling removed?

2023-02-04 02:29 UTC, jasonjewik reviewed
Can I get clarification on why upsampling was removed from the models? I'm still working through the data stuff.

2023-02-04 02:47 UTC, tung-nd commented
Previously we perform downscaling by having a few upsampling layers at the end. However, a better way to do it is to first bilinearly interpolate the input to match the output dimensions, then feed the interpolated input to the network. I found this work better in my previous experiments, and this avoids the need to know the upsampling ratio when constructing the network.

2023-02-04 03:22 UTC, jasonjewik requested changes
@tung-nd I tested this code on MINT2. Can you confirm `test.ipynb` works there? If it works, then delete `test.ipynb` and commit again.

2023-02-04 21:48 UTC, jasonjewik approved these changes

2023-02-04 22:25 UTC, merged