Tutorials split
aditya-grover/climate-learn pull request #57
Opened 2023-02-09 05:26 UTC by bulaienTang

Split into three notebooks:
Data_Processing.ipynb
Model_Training_&_Evaluation.ipynb
Visualization.ipynb

2023-02-09 18:51 UTC, jasonjewik requested changes
Please do the following:
- [x] Delete `docs/.DS_Store`
- [ ] Format your code by running `black .` at the top-level directory

2023-02-09 18:51 UTC, jasonjewik commented on src/climate_learn/utils/visualize.py
> +        # print(x.shape, y.shape)
Remove this comment.

2023-02-09 18:51 UTC, jasonjewik commented on src/climate_learn/utils/visualize.py
> +        # print(x.shape)
Remove this comment.

2023-02-09 18:53 UTC, jasonjewik commented
IMO, the individual feature notebooks should not have as much text. Someone should be able to look at the notebook and understand how to run the code in less than a minute. If they want more details, we can provide that in our documentation or point them to the bigger tutorial notebook. @aditya-grover do you have thoughts on what the tutorial notebooks should look like?

2023-02-10 01:20 UTC, bulaienTang commented
@jasonjewik Please take a look, I made these notebooks more concise

2023-02-10 16:08 UTC, aditya-grover commented
Thanks, Bryan. I was also wondering if we should we have task-specific tutorial notebooks: one for weather forecasting, one for downscaling. I guess it could be part of a different pull request.

2023-02-10 18:52 UTC, bulaienTang commented
No problem, I can create a new PR for task-specific notebooks later. Should we close this one and merge it into the main branch?

2023-02-10 22:38 UTC, aditya-grover commented
Sure. Will let @jasonjewik make the final approval.

2023-02-10 23:40 UTC, jasonjewik commented
lgtm

2023-02-10 23:43 UTC, merged

2023-02-10 23:46 UTC, jasonjewik commented
In a near-future commit, we should include links to run these notebooks somewhere. Perhaps we can host them directly in the docs, or on Google Colab.

2023-02-13 09:37 UTC, prakhar6sharma commented
I know @bulaienTang will work on individual notebooks later but just wanted to point out that currently some of the notebooks don't work for me. I think it is caused because while importing sometimes the import path that we are using is `src.climate_learn` instead of `climate_learn`.  I think for all these tutorial notebooks, we should be consistent.

2023-02-13 18:43 UTC, jasonjewik commented
@prakhar6sharma yes, the iterdatamodule notebook doesn't work at the moment. It's not really a tutorial notebook, it's just there because I wanted to save a code example of how to use the IterDataModule, but I haven't found a proper place to put it yet.